export const projects = [
  {
    id: 1,
    slug: "build-a-new-you",
    title: "Build A New You",
    descKey: "desc2",
    image: "placeholder",
    badge: "Freelance",
    tech: ["Laravel", "Vue.js", "Midtrans", "AWS S3", "OAuth"],
    linkProject: "https://buildanewyou.id/",
    repo: "#",
  },
  {
    id: 2,
    slug: "clipper-ai",
    title: "Clipper-AI",
    descKey: "desc1",
    image: "placeholder",
    badge: "Freelance",
    tech: ["React", "TypeScript", "Python", "FastAPI",],
    linkProject: "https://ai.cuanclip.com/",
    repo: "#",
  },
  {
    id: 3,
    slug: "ticktrack-helpdesk",
    title: "TickTrack (Helpdesk Ticketing System)",
    descKey: "desc3",
    image: "placeholder",
    badge: "Academic",
    tech: ["Laravel", "Vue.js", "Tailwind CSS", "MySQL"],
    linkProject: "#",
    repo: "#",
  },
  {
    id: 4,
    slug: "ecomputer-blog",
    title: "EComputer-Blog",
    descKey: "desc5",
    image: "placeholder",
    badge: "Academic",
    tech: ["HTML5", "CSS3", "JavaScript", "Swiper.js"],
    linkProject: "https://github.com/ptramichsthg/EComputer-Blog",
    repo: "https://github.com/ptramichsthg/EComputer-Blog",
  },
  {
    id: 5,
    slug: "twogunshop",
    title: "TwoGunShop",
    descKey: "desc6",
    image: "placeholder",
    badge: "Academic",
    tech: ["PHP", "MySQL", "Bootstrap 5", "JavaScript", "HTML5", "CSS3", "FontAwesome"],
    linkProject: "https://github.com/ptramichsthg/TwoGunShop",
    repo: "https://github.com/ptramichsthg/TwoGunShop",
  },
  {
    id: 6,
    slug: "bookshelf-api",
    title: "Bookshelf API",
    descKey: "desc7",
    image: "placeholder",
    badge: "Academic",
    tech: ["Node.js", "Hapi.js", "JavaScript", "TailwindCSS", "HTML5"],
    linkProject: "https://github.com/ptramichsthg/bookshelf-api",
    repo: "https://github.com/ptramichsthg/bookshelf-api",
  },
  {
    id: 7,
    slug: "unjani-sinema",
    title: "Unjani Sinema",
    descKey: "desc8",
    image: "placeholder",
    badge: "Academic",
    tech: ["Java", "Java Swing", "MySQL", "NetBeans",],
    linkProject: "https://github.com/ptramichsthg/unjani_sinema",
    repo: "https://github.com/ptramichsthg/unjani_sinema",
  },
  {
    id: 8,
    slug: "goat-adven",
    title: "GoatAdven",
    descKey: "desc9",
    image: "placeholder",
    badge: "Academic",
    tech: ["Java", "JavaFX", "Binary I/O", "Apache Ant", "OOP"],
    linkProject: "https://github.com/ptramichsthg/Goat-Adven",
    repo: "https://github.com/ptramichsthg/Goat-Adven",
  },
]
