export const projects = [
  {
    id: 1,
    slug: "build-a-new-you",
    title: "Build A New You (E-Learning & Bootcamp)",
    descKey: "desc2",
    image: "placeholder",
    tech: ["Laravel 12", "Vue.js 3", "Pinia", "Midtrans", "AWS S3", "OAuth 2.0"],
    linkProject: "https://buildanewyou.id/",
    repo: "#",
  },
  {
    id: 2,
    slug: "clipper-ai",
    title: "Clipper-AI (AI-Driven Video Editing SaaS)",
    descKey: "desc1",
    image: "placeholder", 
    tech: ["React 19", "TypeScript", "Python", "FastAPI", "FFmpeg"],
    linkProject: "https://ai.cuanclip.com/",
    repo: "#",
  },
  {
    id: 3,
    slug: "ticktrack-helpdesk",
    title: "TickTrack (Helpdesk Ticketing System)",
    descKey: "desc3",
    image: "placeholder",
    tech: ["Laravel 11", "Vue.js 3", "Pinia", "Sanctum", "Tailwind CSS", "SQLite"],
    linkProject: "#",
    repo: "#",
  },
  {
    id: 4,
    slug: "ecomputer-blog",
    title: "EComputer-Blog",
    descKey: "desc5",
    image: "placeholder",
    tech: ["HTML5", "CSS3", "JavaScript", "Swiper.js"],
    linkProject: "https://github.com/ptramichsthg/EComputer-Blog",
    repo: "https://github.com/ptramichsthg/EComputer-Blog",
  },
  {
    id: 5,
    slug: "twogunshop",
    title: "TwoGunShop",
    descKey: "desc6",
    image: "placeholder",
    tech: ["PHP", "MySQL", "Bootstrap 5", "JavaScript", "HTML5", "CSS3", "FontAwesome"],
    linkProject: "https://github.com/ptramichsthg/TwoGunShop",
    repo: "https://github.com/ptramichsthg/TwoGunShop",
  },
  {
    id: 6,
    slug: "bookshelf-api",
    title: "Bookshelf API",
    descKey: "desc7",
    image: "placeholder",
    tech: ["Node.js", "Hapi.js", "JavaScript", "TailwindCSS", "HTML5"],
    linkProject: "https://github.com/ptramichsthg/bookshelf-api",
    repo: "https://github.com/ptramichsthg/bookshelf-api",
  },
]
