export const projects = [
  {
    id: 1,
    slug: "build-a-new-you",
    title: "Build A New You",
    descKey: "desc2",
    image: "placeholder",
    badge: "Freelance",
    category: "E-Learning",
    tech: ["Laravel", "Vue.js", "MySQL", "AWS S3"],
    linkProject: "https://buildanewyou.id/",
    repo: "#",
  },
  {
    id: 2,
    slug: "clipper-ai",
    title: "Clipper-AI",
    descKey: "desc1",
    image: "/images/clipper-ai.png",
    badge: "Freelance",
    category: "AI Video",
    tech: ["React.js", "TypeScript", "Python", "FastAPI"],
    linkProject: "https://ai.cuanclip.com/",
    repo: "#",
  },
  {
    id: 11,
    slug: "benvenuto",
    title: "Benvenuto",
    descKey: "desc11",
    image: "/images/benvenuto.png",
    badge: "Web Design",
    category: "Resto",
    tech: ["React", "Framer Motion", "Tailwind", "Vercel"],
    linkProject: "https://benvenuto-alpha.vercel.app/",
    repo: "https://benvenuto-alpha.vercel.app/",
  },
  {
    id: 3,
    slug: "ticktrack-helpdesk",
    title: "TickTrack Helpdesk Ticketing System",
    descKey: "desc3",
    image: "/images/ticktrack.png",
    badge: "Academic",
    category: "Helpdesk",
    tech: ["Laravel", "Vue.js", "Tailwind CSS", "MySQL"],
    linkProject: "https://github.com/ptramichsthg/ticktrack-fe",
    repo: "https://github.com/ptramichsthg/ticktrack-fe",
  },
  {
    id: 10,
    slug: "rasa-rekomendasi",
    title: "Rasa Rekomendasi",
    descKey: "desc10",
    image: "placeholder",
    badge: "Academic",
    tech: ["Laravel", "Tailwind CSS", "Vite", "MySQL"],
    linkProject: "https://github.com/Fauziian/RasaRekomendasi",
    repo: "https://github.com/Fauziian/RasaRekomendasi",
  },
  {
    id: 4,
    slug: "ecomputer-blog",
    title: "EComputer-Blog",
    descKey: "desc5",
    image: "placeholder",
    badge: "Academic",
    tech: ["HTML5", "CSS3", "JavaScript", "Swiper.js"],
    linkProject: "https://github.com/ptramichsthg/EComputer-Blog",
    repo: "https://github.com/ptramichsthg/EComputer-Blog",
  },
  {
    id: 5,
    slug: "twogunshop",
    title: "TwoGunShop",
    descKey: "desc6",
    image: "placeholder",
    badge: "Academic",
    tech: ["PHP", "MySQL", "Bootstrap 5", "JavaScript", "HTML5", "CSS3", "FontAwesome"],
    linkProject: "https://github.com/ptramichsthg/TwoGunShop",
    repo: "https://github.com/ptramichsthg/TwoGunShop",
  },
  {
    id: 6,
    slug: "bookshelf-api",
    title: "Bookshelf API",
    descKey: "desc7",
    image: "placeholder",
    badge: "Academic",
    tech: ["Node.js", "JavaScript", "Tailwind CSS", "HTML5"],
    linkProject: "https://github.com/ptramichsthg/bookshelf-api",
    repo: "https://github.com/ptramichsthg/bookshelf-api",
  },
  {
    id: 7,
    slug: "unjani-sinema",
    title: "Unjani Sinema",
    descKey: "desc8",
    image: "placeholder",
    badge: "Academic",
    tech: ["Java", "MySQL"],
    linkProject: "https://github.com/ptramichsthg/unjani_sinema",
    repo: "https://github.com/ptramichsthg/unjani_sinema",
  },
  {
    id: 8,
    slug: "goat-adven",
    title: "GoatAdven",
    descKey: "desc9",
    image: "placeholder",
    badge: "Academic",
    tech: ["Java", "Apache Ant"],
    linkProject: "https://github.com/ptramichsthg/Goat-Adven",
    repo: "https://github.com/ptramichsthg/Goat-Adven",
  },
]
